# Generated by Django 5.2.11 on 2026-09-05 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Legal/Primary name', max_length=255)),
                ('stage_name', models.CharField(db_index=True, help_text='Public Stage/Artist name', max_length=255)),
                ('profile_image', models.URLField(blank=True, help_text='Image or Avatar URL', max_length=1000, null=True)),
                ('description', models.TextField(blank=True, default='', help_text='Artist bio or notes')),
                ('youtube_channel_id', models.CharField(blank=True, default='', help_text='Linked YouTube Channel ID', max_length=100)),
                ('youtube_channel_url', models.URLField(blank=True, default='', help_text='Full YouTube Channel or Handle URL', max_length=500)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('PENDING', 'Pending Channel')], default='ACTIVE', max_length=20)),
                ('genre', models.CharField(blank=True, default='Music', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Artist',
                'verbose_name_plural': 'Artists',
                'ordering': ['stage_name'],
            },
        ),
        migrations.CreateModel(
            name='YouTubeChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(db_index=True, help_text='Official YouTube Channel ID (e.g. UCxxxxxxxxxxxxxx)', max_length=100, unique=True)),
                ('channel_name', models.CharField(help_text='YouTube Channel Display Title', max_length=255)),
                ('channel_url', models.URLField(help_text='YouTube Channel URL or Handle', max_length=500)),
                ('thumbnail_url', models.URLField(blank=True, default='', max_length=1000)),
                ('description', models.TextField(blank=True, default='')),
                ('uploads_playlist_id', models.CharField(blank=True, default='', help_text='ID of the uploads playlist (UU...)', max_length=100)),
                ('subscriber_count', models.BigIntegerField(default=0, help_text='Total subscribers (approximate by YouTube)')),
                ('total_views', models.BigIntegerField(default=0, help_text='Total channel views')),
                ('video_count', models.IntegerField(default=0, help_text='Total uploaded videos count')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.CharField(choices=[('IDLE', 'Idle'), ('SYNCING', 'Syncing'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='IDLE', max_length=20)),
                ('last_sync_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.OneToOneField(help_text='The artist who owns this YouTube channel', on_delete=django.db.models.deletion.CASCADE, related_name='channel', to='artists.artist')),
            ],
            options={
                'verbose_name': 'YouTube Channel',
                'verbose_name_plural': 'YouTube Channels',
                'ordering': ['-total_views'],
            },
        ),
    ]
