# Generated by Django 5.2.17 on 2026-09-11 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=512)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('uploader', models.CharField(blank=True, max_length=255)),
                ('thumbnail_url', models.URLField(blank=True, max_length=512)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('format', models.CharField(choices=[('mp4_1080p', 'MP4 1080p'), ('mp4_720p', 'MP4 720p'), ('mp4_480p', 'MP4 480p'), ('mp3_320', 'MP3 320kbps'), ('mp3_192', 'MP3 192kbps'), ('mp3_128', 'MP3 128kbps')], default='mp4_1080p', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DOWNLOADING', 'Downloading'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('output_file', models.FileField(blank=True, null=True, upload_to='downloads/')),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('progress_text', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Download Job',
                'verbose_name_plural': 'Download Jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
