# Generated by Django 5.2.17 on 2026-09-11 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadjob',
            name='format',
            field=models.CharField(choices=[('mp3_320', 'MP3 320kbps'), ('wav', 'WAV (Lossless)')], default='mp3_320', max_length=20),
        ),
    ]
