# Generated by Django 5.2.11 on 2026-09-05 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('MILESTONE', 'Milestone Reached'), ('SPIKE_ALERT', 'Growth Spike Alert'), ('SYNC_ERROR', 'Sync Failure'), ('SYSTEM', 'System Alert')], default='SYSTEM', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, default='', max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone_type', models.CharField(choices=[('VIEWS_10K', '10,000 Views'), ('VIEWS_50K', '50,000 Views'), ('VIEWS_100K', '100,000 Views'), ('VIEWS_250K', '250,000 Views'), ('VIEWS_500K', '500,000 Views'), ('VIEWS_1M', '1,000,000 Views'), ('VIEWS_5M', '5,000,000 Views'), ('VIEWS_10M', '10,000,000 Views'), ('CUSTOM', 'Custom Milestone')], max_length=50)),
                ('threshold', models.BigIntegerField(help_text='Target view count reached')),
                ('views_at_milestone', models.BigIntegerField(default=0)),
                ('reached_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('notified', models.BooleanField(default=False)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='videos.video')),
            ],
            options={
                'verbose_name': 'Video Milestone',
                'verbose_name_plural': 'Video Milestones',
                'ordering': ['-reached_at'],
                'unique_together': {('video', 'threshold')},
            },
        ),
    ]
