# Generated by Django 5.2.11 on 2026-09-05 18:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_interval_hours', models.IntegerField(default=6)),
                ('app_timezone', models.CharField(default='UTC', max_length=100)),
                ('default_reporting_period', models.CharField(default='30d', max_length=50)),
                ('spike_alert_threshold', models.IntegerField(default=10000, help_text='Views gained in 24h to trigger spike alert')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
        migrations.CreateModel(
            name='YouTubeApiUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now, unique=True)),
                ('quota_used', models.IntegerField(default=0, help_text='Total estimated quota units consumed today (standard daily limit is 10,000)')),
                ('request_count', models.IntegerField(default=0, help_text='Number of API requests executed')),
                ('last_request_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'YouTube API Usage',
                'verbose_name_plural': 'YouTube API Usages',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name_cached', models.CharField(blank=True, default='', max_length=255)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='RUNNING', max_length=20)),
                ('videos_found', models.IntegerField(default=0)),
                ('new_videos', models.IntegerField(default=0)),
                ('videos_updated', models.IntegerField(default=0)),
                ('snapshots_created', models.IntegerField(default=0)),
                ('duration_seconds', models.FloatField(default=0.0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='artists.youtubechannel')),
            ],
            options={
                'verbose_name': 'Sync Log',
                'verbose_name_plural': 'Sync Logs',
                'ordering': ['-started_at'],
            },
        ),
    ]
