# Generated by Django 5.2.11 on 2026-09-05 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='daily_posting_target',
            field=models.IntegerField(default=10, help_text='Daily content upload target (e.g. 10 contents/day)'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='posting_reminders_enabled',
            field=models.BooleanField(default=True, help_text='Enable desktop notification reminders'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='reminder_end_hour',
            field=models.IntegerField(default=21, help_text='Latest hour to send reminders (0-23, e.g. 21 for 9 PM)'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='reminder_frequency_hours',
            field=models.IntegerField(default=3, help_text='Interval in hours between desktop reminders if target not met'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='reminder_start_hour',
            field=models.IntegerField(default=9, help_text='Earliest hour to send reminders (0-23, e.g. 9 for 9 AM)'),
        ),
    ]
