# Generated by Django 5.2.11 on 2026-09-05 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_video_id', models.CharField(db_index=True, help_text='YouTube Video ID (e.g. dQw4w9WgXcQ)', max_length=50, unique=True)),
                ('title', models.CharField(db_index=True, max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('thumbnail_url', models.URLField(blank=True, default='', max_length=1000)),
                ('published_at', models.DateTimeField(db_index=True, help_text='Release / Upload date')),
                ('duration', models.CharField(blank=True, default='', help_text='ISO 8601 or HH:MM:SS format', max_length=50)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('video_url', models.URLField(max_length=500)),
                ('current_views', models.BigIntegerField(db_index=True, default=0)),
                ('current_likes', models.BigIntegerField(default=0)),
                ('current_comments', models.BigIntegerField(default=0)),
                ('views_today', models.BigIntegerField(default=0)),
                ('views_this_week', models.BigIntegerField(default=0)),
                ('views_this_month', models.BigIntegerField(default=0)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='False if video was deleted or set to private')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(help_text='Artist associated with the video', on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='artists.artist')),
                ('channel', models.ForeignKey(help_text='Channel the video was uploaded to', on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='artists.youtubechannel')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
                'ordering': ['-current_views'],
            },
        ),
        migrations.CreateModel(
            name='ChannelStatisticSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(db_index=True)),
                ('subscriber_count', models.BigIntegerField(default=0)),
                ('total_views', models.BigIntegerField(default=0)),
                ('video_count', models.IntegerField(default=0)),
                ('subscriber_change', models.BigIntegerField(default=0)),
                ('view_change', models.BigIntegerField(default=0)),
                ('video_change', models.IntegerField(default=0)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='artists.youtubechannel')),
            ],
            options={
                'verbose_name': 'Channel Statistic Snapshot',
                'verbose_name_plural': 'Channel Statistic Snapshots',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['channel', 'recorded_at'], name='videos_chan_channel_b5c089_idx')],
            },
        ),
        migrations.CreateModel(
            name='VideoStatisticSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(db_index=True)),
                ('views', models.BigIntegerField(default=0)),
                ('likes', models.BigIntegerField(default=0)),
                ('comments', models.BigIntegerField(default=0)),
                ('views_change', models.BigIntegerField(default=0, help_text='Estimated views gained since last snapshot')),
                ('likes_change', models.BigIntegerField(default=0)),
                ('comments_change', models.BigIntegerField(default=0)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='videos.video')),
            ],
            options={
                'verbose_name': 'Video Statistic Snapshot',
                'verbose_name_plural': 'Video Statistic Snapshots',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['video', 'recorded_at'], name='videos_vide_video_i_95cc2d_idx')],
            },
        ),
    ]
