# Generated by Django 5.2.17 on 2026-09-07 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeOAuthAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(db_index=True, help_text='Official YouTube Channel ID (e.g. UCxxxxxxxxxxxxxx)', max_length=100, unique=True)),
                ('channel_title', models.CharField(help_text='Channel name', max_length=255)),
                ('channel_custom_url', models.CharField(blank=True, default='', help_text='Channel handle or custom URL (e.g. @artist)', max_length=255)),
                ('thumbnail_url', models.URLField(blank=True, default='', max_length=1000)),
                ('subscriber_count', models.BigIntegerField(default=0)),
                ('video_count', models.IntegerField(default=0)),
                ('token_json', models.JSONField(default=dict, help_text='OAuth 2.0 tokens (access_token, refresh_token, client_id, client_secret, token_uri, scopes)')),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_channel', models.ForeignKey(blank=True, help_text='Linked YouTube Channel in the Analytics database (if matched)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oauth_accounts', to='artists.youtubechannel')),
            ],
            options={
                'verbose_name': 'YouTube OAuth Account',
                'verbose_name_plural': 'YouTube OAuth Accounts',
                'ordering': ['-is_default', 'channel_title'],
            },
        ),
        migrations.CreateModel(
            name='PublishingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='YouTube video title (max 100 characters)', max_length=100)),
                ('description', models.TextField(blank=True, default='', help_text='YouTube video description (max 5,000 characters)')),
                ('tags', models.JSONField(blank=True, default=list, help_text='List of keyword tags')),
                ('category_id', models.CharField(default='10', help_text='YouTube Category ID (10=Music, 24=Entertainment, 22=People & Blogs)', max_length=10)),
                ('privacy_status', models.CharField(choices=[('private', 'Private Draft (Recommended)'), ('unlisted', 'Unlisted (Shareable Preview Link)'), ('public', 'Public (Instant Release)'), ('scheduled', 'Scheduled Release')], default='private', max_length=20)),
                ('publish_at', models.DateTimeField(blank=True, help_text='Scheduled release timestamp (UTC). Required if privacy_status is SCHEDULED', null=True)),
                ('made_for_kids', models.BooleanField(default=False)),
                ('embeddable', models.BooleanField(default=True)),
                ('video_file_path', models.CharField(help_text='Absolute local filesystem path to the .mp4 video', max_length=1000)),
                ('thumbnail_path', models.CharField(blank=True, default='', help_text='Optional local path to custom thumbnail image', max_length=1000)),
                ('source_type', models.CharField(choices=[('LONG_MIX', 'Non-Stop Long Mix'), ('SHORT_VIDEO', 'Viral Short / Clip'), ('LYRIC_VIDEO', 'Synced Lyrics Video'), ('VIDEO_LOOP', '1-Hour Study / Chill Loop'), ('CUSTOM_FILE', 'Custom Media Upload')], default='CUSTOM_FILE', max_length=30)),
                ('source_id', models.IntegerField(blank=True, help_text='ID of the Studio project in Django database', null=True)),
                ('source_chop_index', models.IntegerField(blank=True, help_text='Chop/part index if source is a Short video project', null=True)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('UPLOADING', 'Uploading'), ('PROCESSING', 'Processing'), ('SUCCESS', 'Completed / Published'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='QUEUED', max_length=20)),
                ('progress_percent', models.IntegerField(default=0)),
                ('bytes_uploaded', models.BigIntegerField(default=0)),
                ('total_bytes', models.BigIntegerField(default=0)),
                ('youtube_video_id', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('youtube_url', models.URLField(blank=True, default='', max_length=500)),
                ('error_message', models.TextField(blank=True, default='')),
                ('retry_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(blank=True, help_text='Target YouTube channel account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='publishing.youtubeoauthaccount')),
            ],
            options={
                'verbose_name': 'Publishing Job',
                'verbose_name_plural': 'Publishing Jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
