# Generated by Django 5.2.17 on 2026-09-07 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishingjob',
            name='upload_engine',
            field=models.CharField(choices=[('API_V3', 'YouTube Data API v3 (Official API)'), ('BROWSER_AUTOMATION', 'Browser Automation (Zero Quota)'), ('STUDIO_DISPATCHER', '1-Click Studio Assistant (Clipboard)')], default='API_V3', help_text='Engine / protocol used to upload video to YouTube', max_length=30),
        ),
    ]
