# Generated by Django 5.2.11 on 2026-09-05 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='My 1-Hour Chill Loop', max_length=255)),
                ('audio_file', models.FileField(upload_to='studio/audio/')),
                ('cover_image', models.ImageField(upload_to='studio/covers/')),
                ('video_format', models.CharField(choices=[('1HOUR_LOOP', '1-Hour Study/Chill Loop (60 Min)'), ('VISUALIZER', '1080p Official Visualizer (Full Song)'), ('SHORT', '15s YouTube Shorts Hook (9:16 Vertical)')], default='1HOUR_LOOP', max_length=20)),
                ('output_video', models.FileField(blank=True, null=True, upload_to='studio/videos/')),
                ('duration_seconds', models.IntegerField(default=3600)),
                ('render_status', models.CharField(choices=[('PENDING', 'Pending'), ('RENDERING', 'Rendering'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Video Studio Project',
                'verbose_name_plural': 'Video Studio Projects',
                'ordering': ['-created_at'],
            },
        ),
    ]
