# Generated by Django 5.2.17 on 2026-09-06 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LongMixProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='My Non-Stop Music Mix', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='studio/mix_covers/')),
                ('transition_curve', models.CharField(choices=[('qsin', 'Smooth Quarter-Sine / Equal-Power (Recommended)'), ('tri', 'Triangular Linear Fade'), ('lin', 'Linear Crossfade'), ('exp', 'Exponential Fade (Smooth Fade-Out)'), ('fast', 'Quick Club Cut (1.5s Overlap)')], default='qsin', max_length=20)),
                ('crossfade_seconds', models.IntegerField(default=6)),
                ('render_video', models.BooleanField(default=True)),
                ('output_audio', models.FileField(blank=True, null=True, upload_to='studio/mix_audio/')),
                ('output_video', models.FileField(blank=True, null=True, upload_to='studio/mix_videos/')),
                ('duration_seconds', models.IntegerField(default=0)),
                ('track_count', models.IntegerField(default=0)),
                ('tracklist_data', models.JSONField(blank=True, default=list)),
                ('render_status', models.CharField(choices=[('PENDING', 'Pending'), ('RENDERING', 'Rendering'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Non-Stop Long Mix Project',
                'verbose_name_plural': 'Non-Stop Long Mix Projects',
                'ordering': ['-created_at'],
            },
        ),
    ]
