# Generated by Django 5.2.17 on 2026-09-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0002_longmixproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortVideoProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='My Viral Shorts & Reels', max_length=255)),
                ('source_type', models.CharField(choices=[('VIDEO', 'Long Video Upload (.mp4, .mov, .mkv)'), ('AUDIO_COVER', 'Audio + Cover Art Track')], default='VIDEO', max_length=20)),
                ('source_video', models.FileField(blank=True, null=True, upload_to='studio/shorts_source/')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='studio/shorts_audio/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='studio/shorts_covers/')),
                ('aspect_mode', models.CharField(choices=[('BLURRED_FIT', 'Blurred Ambient Background (9:16 Vertical)'), ('CENTER_CROP', 'Center Crop 9:16 (Fill Full Screen)'), ('LETTERBOX', 'Letterbox (Black Bars)')], default='BLURRED_FIT', max_length=20)),
                ('theme_style', models.CharField(choices=[('VIRAL_HOOK', 'Viral Hook Banner + Smart Badges'), ('CLEAN', 'Modern Minimal (No Overlays)'), ('GLOW_NEON', 'Cyber Neon Glow'), ('CHILL_LOFI', 'Aesthetic Lo-Fi / Ambient')], default='VIRAL_HOOK', max_length=30)),
                ('duration_seconds', models.FloatField(default=0.0)),
                ('chop_count', models.IntegerField(default=0)),
                ('chops_data', models.JSONField(blank=True, default=list)),
                ('output_video', models.FileField(blank=True, null=True, upload_to='studio/shorts_output/')),
                ('render_status', models.CharField(choices=[('PENDING', 'Pending'), ('RENDERING', 'Rendering'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Short Video Project',
                'verbose_name_plural': 'Short Video Projects',
                'ordering': ['-created_at'],
            },
        ),
    ]
