# Generated by Django 5.2.17 on 2026-09-07 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0003_shortvideoproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='LyricVideoProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='My Song Lyrics', max_length=255)),
                ('artist_name', models.CharField(blank=True, default='', max_length=255)),
                ('audio_file', models.FileField(upload_to='studio/lyrics_audio/')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='studio/lyrics_bg/')),
                ('background_video', models.FileField(blank=True, null=True, upload_to='studio/lyrics_bg_video/')),
                ('lyrics_raw_text', models.TextField(blank=True, default='')),
                ('lyrics_data', models.JSONField(blank=True, default=list)),
                ('animation_style', models.CharField(choices=[('KARAOKE_WIPE', 'Karaoke Color Wipe & Glow'), ('ROLLING_3LINE', 'Smooth 3-Line Rolling Display'), ('CYBER_NEON', 'Cyber Neon Glow'), ('CINEMATIC', 'Cinematic Minimal Serif')], default='KARAOKE_WIPE', max_length=30)),
                ('aspect_ratio', models.CharField(choices=[('16:9', '16:9 Landscape (YouTube Full HD 1080p)'), ('9:16', '9:16 Vertical (Shorts / Reels / TikTok)')], default='16:9', max_length=10)),
                ('font_family', models.CharField(default='Arial', max_length=50)),
                ('font_size', models.IntegerField(default=48)),
                ('highlight_color', models.CharField(default='#00E5FF', max_length=20)),
                ('text_color', models.CharField(default='#FFFFFF', max_length=20)),
                ('position_mode', models.CharField(default='CENTER', max_length=20)),
                ('output_video', models.FileField(blank=True, null=True, upload_to='studio/lyrics_output/')),
                ('duration_seconds', models.FloatField(default=0.0)),
                ('render_status', models.CharField(choices=[('PENDING', 'Pending'), ('RENDERING', 'Rendering'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lyrics Video Project',
                'verbose_name_plural': 'Lyrics Video Projects',
                'ordering': ['-created_at'],
            },
        ),
    ]
