# Generated by Django 5.2.11 on 2026-09-07 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0004_lyricvideoproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='lyricvideoproject',
            name='source_type',
            field=models.CharField(choices=[('AUDIO_IMAGE', 'Audio Track + Cover Art'), ('VIDEO', 'Source Video File (.mp4, .mov, .webm)')], default='AUDIO_IMAGE', max_length=20),
        ),
        migrations.AlterField(
            model_name='lyricvideoproject',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='studio/lyrics_audio/'),
        ),
    ]
