# Generated by Django 5.2.17 on 2026-09-08 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0005_lyricvideoproject_source_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='longmixproject',
            name='render_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RENDERING', 'Rendering'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='lyricvideoproject',
            name='render_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RENDERING', 'Rendering'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='shortvideoproject',
            name='render_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RENDERING', 'Rendering'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='videoproject',
            name='render_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RENDERING', 'Rendering'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
