# Generated by Django 5.2.17 on 2026-09-08 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0006_alter_longmixproject_render_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortvideoproject',
            name='crop_focal_percent',
            field=models.IntegerField(default=50),
        ),
    ]
