# Generated by Django 5.2.17 on 2026-09-08 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0007_shortvideoproject_crop_focal_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='lyricvideoproject',
            name='bg_opacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lyricvideoproject',
            name='font_italic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lyricvideoproject',
            name='font_scale_x',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='lyricvideoproject',
            name='font_scale_y',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='lyricvideoproject',
            name='font_weight',
            field=models.CharField(default='bold', max_length=10),
        ),
        migrations.AddField(
            model_name='lyricvideoproject',
            name='letter_spacing',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='lyricvideoproject',
            name='line_height',
            field=models.FloatField(default=1.4),
        ),
        migrations.AddField(
            model_name='lyricvideoproject',
            name='text_shadow_depth',
            field=models.FloatField(default=2.0),
        ),
        migrations.AddField(
            model_name='lyricvideoproject',
            name='text_stroke_width',
            field=models.FloatField(default=2.5),
        ),
        migrations.AddField(
            model_name='lyricvideoproject',
            name='text_transform',
            field=models.CharField(default='none', max_length=15),
        ),
        migrations.AlterField(
            model_name='lyricvideoproject',
            name='animation_style',
            field=models.CharField(choices=[('KARAOKE_WIPE', 'Karaoke Color Wipe & Glow'), ('ROLLING_3LINE', 'Smooth 3-Line Rolling Display'), ('CYBER_NEON', 'Cyber Neon Glow'), ('CINEMATIC', 'Cinematic Minimal Serif'), ('BOUNCE_IN', 'Bounce Pop-In'), ('TYPEWRITER', 'Typewriter Reveal'), ('WAVE_PULSE', 'Wave Color Pulse'), ('SLIDE_UP', 'Smooth Slide Up')], default='KARAOKE_WIPE', max_length=30),
        ),
    ]
