# Generated by Django 5.2.17 on 2026-09-08 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0008_lyricvideoproject_bg_opacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortvideoproject',
            name='hook_position',
            field=models.CharField(choices=[('TOP', 'Top (Header Overlay)'), ('CENTER', 'Center (Focal Drop)'), ('BOTTOM', 'Bottom (Lower Third / CTA Area)')], default='TOP', max_length=20),
        ),
    ]
