# Generated by Django 5.2.17 on 2026-09-08 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0009_shortvideoproject_hook_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lyricvideoproject',
            name='position_mode',
            field=models.CharField(choices=[('CENTER', 'Center'), ('BOTTOM', 'Bottom Third'), ('TOP', 'Top')], default='CENTER', max_length=20),
        ),
    ]
