# Generated by Django 5.2.17 on 2026-09-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0010_alter_lyricvideoproject_position_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='lyricvideoproject',
            name='cover_layout',
            field=models.CharField(
                choices=[('AMBIENT', 'Ambient / Centered Artwork'), ('FULL', 'Full Cover Background')],
                default='AMBIENT',
                max_length=20,
            ),
        ),
    ]
