# Generated by Django 5.2.17 on 2026-09-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0011_lyricvideoproject_cover_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='lyricvideoproject',
            name='cover_size',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='lyricvideoproject',
            name='cover_blur',
            field=models.FloatField(default=8.0),
        ),
        migrations.AddField(
            model_name='lyricvideoproject',
            name='cover_opacity',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='lyricvideoproject',
            name='cover_offset',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='lyricvideoproject',
            name='cover_brightness',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='lyricvideoproject',
            name='cover_contrast',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='lyricvideoproject',
            name='cover_saturation',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='lyricvideoproject',
            name='cover_vignette',
            field=models.FloatField(default=0.0),
        ),
    ]
