# Generated by Django 5.2.11 on 2026-09-10 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0012_lyricvideoproject_cover_effects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lyricvideoproject',
            name='animation_style',
            field=models.CharField(choices=[('KARAOKE_WIPE', 'Karaoke Color Wipe & Glow'), ('ROLLING_3LINE', 'Smooth 3-Line Rolling Display'), ('CYBER_NEON', 'Cyber Neon Glow'), ('CINEMATIC', 'Cinematic Minimal Serif'), ('BOUNCE_IN', 'Bounce Pop-In'), ('TYPEWRITER', 'Typewriter Reveal'), ('WAVE_PULSE', 'Wave Color Pulse'), ('SLIDE_UP', 'Smooth Slide Up'), ('CLIP_REVEAL', 'Clip Reveal Wipe'), ('WORD_DROP', 'Word Drop Cascade'), ('SPLASH_SETTLE', 'Splash & Settle'), ('GHOST_ECHO', 'Ghost Echo'), ('EXPLODE_OUT', 'Explode Out'), ('SPIN_IN', 'Spin In')], default='KARAOKE_WIPE', max_length=30),
        ),
    ]
