# Generated by Django 5.2.11 on 2026-09-10 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0014_add_missing_animation_styles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lyricvideoproject',
            name='animation_style',
            field=models.CharField(choices=[('KARAOKE_WIPE', 'Karaoke Color Wipe & Glow'), ('ROLLING_3LINE', 'Smooth 3-Line Rolling Display'), ('PLAYFUL_POP', 'Playful Pop'), ('BUBBLE_BOUNCE', 'Bubble Bounce'), ('DREAMY_DRIFT', 'Dreamy Drift'), ('NEON_GLOW', 'Neon Glow'), ('HANDWRITTEN_INK', 'Handwritten Ink'), ('RETRO_VHS', 'Retro VHS'), ('VINTAGE_COUNTRY', 'Vintage Country'), ('CYBER_NEON', 'Cyber Neon Glow'), ('CINEMATIC', 'Cinematic Minimal Serif'), ('BOUNCE_IN', 'Bounce Pop-In'), ('TYPEWRITER', 'Typewriter Reveal'), ('WAVE_PULSE', 'Wave Color Pulse'), ('SLIDE_UP', 'Smooth Slide Up')], default='KARAOKE_WIPE', max_length=30),
        ),
    ]
