# Generated by Django 5.2.11 on 2026-09-05 21:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0001_initial'),
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentUploadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title or description of the content', max_length=500)),
                ('platform', models.CharField(choices=[('youtube_short', 'YouTube Shorts'), ('youtube_video', 'YouTube Video'), ('tiktok', 'TikTok'), ('instagram_reel', 'Instagram Reel'), ('track_release', 'Track / Single Release'), ('other', 'Other Content')], db_index=True, default='youtube_short', max_length=50)),
                ('url', models.URLField(blank=True, default='', help_text='Direct link to content (optional)', max_length=1000)),
                ('posted_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Time of publication / upload')),
                ('notes', models.TextField(blank=True, default='', help_text='Optional remarks, tags, or campaign notes')),
                ('is_auto_synced', models.BooleanField(default=False, help_text='True if automatically imported from YouTube API')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(blank=True, help_text='Associated artist (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_upload_logs', to='artists.artist')),
                ('video', models.ForeignKey(blank=True, help_text='Linked YouTube video record if auto-synced', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upload_logs', to='videos.video')),
            ],
            options={
                'verbose_name': 'Content Upload Log',
                'verbose_name_plural': 'Content Upload Logs',
                'ordering': ['-posted_at'],
            },
        ),
    ]
